#:schema node_modules/wrangler/config-schema.json
name = "clickjack-attack"
pages_build_output_dir = "dist"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
ALLOWED_FRAME_SRC = "'self' https://clickjack-attack.pages.dev https://clickjack-target.pages.dev"
ALLOWED_FRAME_ANCESTORS = "'self' https://petertraunfeld.com https://clickjack-attack.pages.dev"