#:schema node_modules/wrangler/config-schema.json
name = "clickjack-target"
pages_build_output_dir = "frontend"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
ALLOWED_FRAME_ANCESTORS = "'self' https://petertraunfeld.com https://clickjack-attack.pages.dev "
ALLOWED_ORIGIN = "'self'"